#!/usr/bin/env python3
"""Export V4 tasks as OmniGibson environment + custom-robot scene definitions.

The source of truth is ../tasks.modified.json.  The exported files deliberately
separate the OmniGibson-native environment configuration from custom robot
instances.  This avoids claiming that Isaac-only robot USDs are built-in
OmniGibson robots.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


HERE = Path(__file__).resolve().parent
V4_ROOT = HERE.parent
REPO_ROOT = V4_ROOT.parents[1]
TASKS_PATH = V4_ROOT / "tasks.modified.json"
STAGING_DIR = V4_ROOT / "isaac5" / "staging_scenes"
BEHAVIOR_DATASET = REPO_ROOT / "vendor" / "BEHAVIOR-1K" / "datasets" / "behavior-1k-assets"

ROBOT_PREFIXES = {
    "jackal": ("push_car", "v4_jackal_push", "differential_drive"),
    "ridgeback": ("robot_arm", "v4_ridgeback_ur5_suction", "differential_drive_plus_ur5"),
    "crazyflie": ("drone", "v4_crazyflie_bottom_suction", "kinematic_3d"),
    "crx10ial": ("checkpoint_arm", "v4_crx10ial_suction", "fixed_arm"),
}

# The V4 role labels include task-specific suction / cargo extensions. These
# are the officially imported OG base models underneath those extensions.
OG_BASE_MODELS = {
    "pull_car": "v4_jackal",
    "push_car": "v4_jackal",
    "robot_arm": "v4_ridgeback_ur5",
    "drone": "v4_crazyflie_cf2x",
    "checkpoint_arm": "v4_fanuc_crx10ial",
}


def behavior_activity_name(task_id: str) -> str:
    """Match the local BEHAVIOR registry name generated by registration tool."""
    return "v4_" + task_id.lower().replace("-", "_")


def rel(path: Path) -> str:
    """Return a portable repository-relative path."""
    try:
        return path.resolve().relative_to(REPO_ROOT.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def parse_stage_robots(stage_path: Path) -> list[dict[str, Any]]:
    """Read authored root transforms from a V4 staging USDA without pxr/Isaac."""
    if not stage_path.exists():
        return []
    text = stage_path.read_text(encoding="utf-8")
    starts = list(re.finditer(r'^\s*def Xform "([^"]+)" \(', text, re.MULTILINE))
    robots: list[dict[str, Any]] = []
    for index, match in enumerate(starts):
        name = match.group(1)
        lowered = name.lower()
        matched = next((key for key in ROBOT_PREFIXES if lowered.startswith(key)), None)
        if not matched:
            continue
        block_end = starts[index + 1].start() if index + 1 < len(starts) else len(text)
        block = text[match.start() : block_end]
        role, model, controller = ROBOT_PREFIXES[matched]
        asset = re.search(r"prepend references = @([^@]+)@", block)
        xyz = re.search(r"double3 xformOp:translate = \(([^)]+)\)", block)
        quat = re.search(r"quatd xformOp:orient = \(([^)]+)\)", block)
        scale = re.search(r"double3 xformOp:scale = \(([^)]+)\)", block)
        station = re.search(r"_[sgh]\d+_([mgh]\d+)(?:_|$)", lowered)
        def numbers(found: re.Match[str] | None, default: list[float]) -> list[float]:
            return [float(x.strip()) for x in found.group(1).split(",")] if found else default
        robots.append(
            {
                "name": name,
                "role": role,
                "custom_robot_model": model,
                "omnigibson_base_model": OG_BASE_MODELS[role],
                "locomotion_or_control": controller,
                "station_hint": station.group(1).upper() if station else None,
                "usd_reference": asset.group(1) if asset else None,
                "position": numbers(xyz, [0.0, 0.0, 0.0]),
                "orientation_wxyz": numbers(quat, [1.0, 0.0, 0.0, 0.0]),
                "scale": numbers(scale, [1.0, 1.0, 1.0]),
            }
        )
    return robots


def normalise_asset(reference: str | None) -> str | None:
    if not reference:
        return None
    # Relative references in a staging scene are relative to isaac5/staging_scenes.
    if reference.startswith(("http://", "https://", "omniverse://", "Isaac/")):
        return reference
    return rel((STAGING_DIR / reference).resolve())


def robot_catalog(robot_roles: dict[str, Any]) -> dict[str, Any]:
    catalog: dict[str, Any] = {}
    for role, spec in robot_roles.items():
        catalog[role] = {
            "v4_model": {
                "pull_car": "v4_jackal_pull_suction",
                "push_car": "v4_jackal_push",
                "robot_arm": "v4_ridgeback_ur5_suction",
                "drone": "v4_crazyflie_bottom_suction",
                "checkpoint_arm": "v4_crx10ial_suction",
            }[role],
            "usd_asset": spec["asset"],
            "capability": spec["capability"],
            "runtime_tool": spec["runtime_tool"],
            "omnigibson_base_model": OG_BASE_MODELS[role],
        }
    return catalog


def current_scene_state(scene_name: str) -> str:
    """Resolve a V4 scene state against the installed BEHAVIOR-1K dataset."""
    path = BEHAVIOR_DATASET / "scenes" / scene_name / "json" / f"{scene_name}_best.json"
    return rel(path)


def export_task(task: dict[str, Any], scenario: dict[str, Any], data: dict[str, Any]) -> dict[str, Any]:
    task_id = task["id"]
    staged = parse_stage_robots(STAGING_DIR / f"{task_id}.usda")
    for robot in staged:
        robot["usd_reference"] = normalise_asset(robot["usd_reference"])
    routes = task["routes"]
    required_roles = sorted({role for package in task["packages"] for role in package["required_robot_roles"]})
    staged_roles = sorted({robot["role"] for robot in staged})
    return {
        "$schema": "v4-omnigibson-scene-definition/v1",
        "id": task_id,
        "generated_from": {
            "task_design": rel(TASKS_PATH),
            "behavior_scene_state": current_scene_state(scenario["scene"]),
            "legacy_behavior_scene_state": scenario["scene_json"],
            "behavior_bddl_binding": scenario["behavior_bddl_binding"],
            "task_bddl_problem": task["bddl_problem"],
            "isaac_staging_scene": rel(STAGING_DIR / f"{task_id}.usda"),
        },
        "omnigibson_environment_config": {
            "scene": {
                "type": "InteractiveTraversableScene",
                "scene_model": scenario["scene"],
                "scene_source": "OG",
                "include_robots": True,
                "trav_map_resolution": 0.1,
                "trav_map_erosion": 2,
                "trav_map_with_objects": True,
                "build_graph": True,
            },
            "robots": [],
            "objects": [],
            "task": {
                "type": "BehaviorTask",
                # BEHAVIOR's official task API loads BDDL by activity name,
                # not by arbitrary filename.  register_v4_behavior_activities.py
                # creates v4_<task-id>/problem0.bddl in the local BDDL registry.
                "activity_name": behavior_activity_name(task_id),
                "activity_definition_id": 0,
                "online_object_sampling": True,
                "use_presampled_robot_pose": False,
                "highlight_task_relevant_objects": False,
            },
        },
        "custom_robot_import": {
            "status": "base_models_registered_v4_extensions_pending",
            "reason": "Official-source Jackal, Ridgeback-UR5, Crazyflie and FANUC base RobotDefinitions are registered locally. The V4 suction cups, cargo plate, scale adjustments and task-specific policies remain explicit extensions.",
            "target_api": "OmniGibson 5.1+ data-driven RobotDefinition import",
            "local_omnigibson_compatibility": "registered locally after running omnigibson_definitions/import_official_v4_robots.sh and install_v4_robot_definitions.py in behavior51 (BEHAVIOR-1K v3.9.2 / Isaac Sim 5.1.0). The legacy COHERENT/OmniGibson tree must not be added to PYTHONPATH.",
            "required_before_loading": [
                "Attach the V4 suction cup / cargo plate extensions to the registered base model when that V4 role requires them.",
                "Preserve V4 task scale and action semantics when adding the base model to omnigibson_environment_config.robots.",
            ],
            "robot_models": robot_catalog(data["robot_roles"]),
            "instances_from_isaac_staging_scene": staged,
            "role_coverage": {
                "task_required_roles": required_roles,
                "roles_present_in_staging_scene": staged_roles,
                "missing_task_roles_from_staging": sorted(set(required_roles) - set(staged_roles)),
            },
        },
        "v4_task_semantics": {
            "cell": task["cell"],
            "parallel_work_streams": task["parallel_work_streams"],
            "participation": task["participation"],
            "box_mass_kg": task["box_mass_kg"],
            "execution_policy": task["execution_policy"],
            "robot_ability_profile": task.get("robot_ability_profile", {}),
            "packages": task["packages"],
            "routes": routes,
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=HERE / "generated")
    args = parser.parse_args()
    data = json.loads(TASKS_PATH.read_text(encoding="utf-8"))
    scenarios = {item["id"]: item for item in data["scenarios"]}
    args.output_dir.mkdir(parents=True, exist_ok=True)
    index: list[dict[str, str]] = []
    for task in data["tasks"]:
        result = export_task(task, scenarios[task["scenario"]], data)
        out = args.output_dir / f"{task['id']}.og_scene.json"
        out.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
        index.append({"id": task["id"], "file": out.name, "scene": task["scene"]})
    (args.output_dir / "index.json").write_text(json.dumps(index, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(index)} definitions to {args.output_dir}")


if __name__ == "__main__":
    main()
